name: build-server

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    types: [labeled, synchronize]
        
jobs:
  launch:
    runs-on: build-server
    if: | 
       github.event.inputs.skip_launch == '' 
         && (github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'safe to build'))
    strategy:
      matrix:
        type: ['V','P']
    steps:
      - uses: actions/checkout@v2
        if: ${{ github.event_name == 'pull_request_target' }}
        name: checkout (pull request)
        with:
          clean: false
          # pull requests require explicitly using the pr sha
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v2
        if: ${{ github.event_name != 'pull_request_target' }}
        name: checkout
        with:
          clean: false
      - name: Build rg351${{ matrix.type }}
        run: |
            set -e
            if [[ -n "${{ github.event.inputs.skip_build }}" ]]; then
               echo "skipping build due to parameters"
               exit 0
            fi
            sudo docker run --pull always --rm --user $(id -u $(whoami)) -v $(pwd):/work 351build/351elec-build make RG351${{ matrix.type }}
            #For PR builds, we only keep tar files to limit file transfer costs
            rm -rf release/aarch64/RG351*/*.system
            rm -rf release/aarch64/RG351*/*.img.gz
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-${{ matrix.type }}
          path: |
            release/aarch64/RG351${{ matrix.type }}/
