# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: launch real builder
        run: |
            echo "Run ID: ${GITHUB_RUN_ID}"
            docker version
            docker run -e GH_TOKEN=${{ secrets.GH_TOKEN }} \
                       -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY}} \
                       -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID}} \
                       -e SSH_PUBLIC_KEY=${{ secrets.SSH_PUBLIC_KEY}} \
                       pkegg/api:latest create-instance

             
