# This is a basic workflow to help you get started with Actions

name: rg351v-self-hosted

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  launch:
    runs-on: ubuntu-20.04
    steps:
      - name: launch real builder
        run: |
            echo "Run ID: ${GITHUB_RUN_ID} ${{ env.GITHUB_RUN_ID }}"
            export LABEL=full-build
            DOCKER_IMAGE="pkegg/api:latest" 
            docker run -e GH_TOKEN=${{ secrets.GH_TOKEN }} \
                -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                -e SSH_PUBLIC_KEY="${{ secrets.SSH_PUBLIC_KEY }}" \
                ${DOCKER_IMAGE} create-instance
  build:
    needs: launch
    # The type of runner that the job will run on
    runs-on: full-build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          clean: false

      # Runs a set of commands using the runners shell
      - name: Build rg351v
        run: |
            set +e
            VERBOSE=no make RG351V
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: |
            release
        # Runs a set of commands using the runners shell
      - name: Shutdown runner
        if: always()
        run: |
            echo "Shutting down runner in 30 seconds..."
            nohup sudo /bin/bash -c '/bin/sleep 30 && /usr/sbin/init 0' &
