name: sync-upstream
on:
  schedule:
    - cron:  '0 7,14,21 * * *'
    # scheduled at 07:00 every Monday and Thursday

  workflow_dispatch:  # click the button on Github repo!


jobs:
  sync_with_upstream:
    runs-on: ubuntu-20.04
    name: sync with upstream
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: 351ELEC/351ELEC      # set the upstream repo
          upstream-branch: main   # set the upstream branch to merge from
          branch: main          # set the branch to merge to
          token: ${{ secrets.GITHUB_TOKEN }}
