name: sync-upstream
on:
  schedule:
    - cron:  '0 7,14,21 * * *'
    # scheduled at 07:00 every Monday and Thursday

  workflow_dispatch:  # click the button on Github repo!


jobs:
  sync:
    runs-on: ubuntu-20.04
    name: sync
    outputs:
      ahead: ${{ steps.sync.outputs.test }}
      test: ${{ steps.step1.outputs.test }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main             # set the branch to merge to
          fetch-depth: 0
      - id: step1
        run: |
          set -e
          upstream_branch=main
          branch=main
          git config --global user.email "mseashor@gmail.com"
          git config --global user.name "sync-with-upstream"
          git remote add -f upstream "https://github.com/351ELEC/351ELEC.git"
          ahead=$(git rev-list --count ${branch}..upstream/${upstream_branch})
          echo "::set-output name=test::${ahead}"
      - name: sync
        shell: bash
        run: |
           set -e
           #upstream_branch=main
           #branch=main
           #git config --global user.email "mseashor@gmail.com"
           #git config --global user.name "sync-with-upstream"
           #git remote add -f upstream "https://github.com/351ELEC/351ELEC.git"
           #upstream_hash=$(git rev-parse --short refs/remotes/upstream/${upstream_branch})
           #current_hash=$(git rev-parse --short refs/heads/${branch})
           #ahead=$(git rev-list --count upstream/${upstream_branch}..${branch})
           ahead=10
           #echo "ahead: ${ahead}"
           #echo "upstream hash: ${upstream_hash} current hash:  ${current_hash}"
           #git remote -v
           #git branch --all
           #git config --list
           #git checkout ${branch}
           #git merge upstream/${upstream_branch}
           #git push
           if [[ "${ahead}" == "10" ]]; then
             echo "::set-output name=test::ten"
           else
             echo "::set-output name=test::zero"
           fi
  trigger:
      runs-on: ubuntu-20.04
      needs: sync
      steps:
        - run: echo ${{needs.sync.outputs.test}}
        - name: run-update
          if: ${{ needs.sync.outputs.test == "0" }}
          run: |
              set -e
              changes="${{ needs.sync.outputs.test }}"
              if [[ "$changes" != "0" ]]; then
                 echo "changes!"
              else
                 echo "no changes..."
              fi
