name: sync-upstream
on:
  schedule:
    - cron:  '0 7,14,21 * * *'
    # scheduled at 07:00 every Monday and Thursday

  workflow_dispatch:  # click the button on Github repo!


jobs:
  sync_with_upstream:
    runs-on: ubuntu-20.04
    name: sync with upstream
    steps: 

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main             # set the branch to merge to
          fetch-depth: 0 
      - name: Merge Upstream
        shell: bash
        run: |
           git config --global user.email "mseashor@gmail.com"
           git config --global user.name "sync-with-upstream"
           git remote add -f upstream "https://github.com/351ELEC/351ELEC.git"
           git remote -v
           git branch --all
           git config --list
           git checkout main
           git merge upstream/main
           git push  
